package mx.ipn.bean;
// Generated 2/10/2018 11:29:29 AM by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private String curp;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private String correoElectronico;
     private byte activo;

    public Profesor() {
    }

	
    public Profesor(String curp, String nombre, String primerApellido, String correoElectronico, byte activo) {
        this.curp = curp;
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.correoElectronico = correoElectronico;
        this.activo = activo;
    }
    public Profesor(String curp, String nombre, String primerApellido, String segundoApellido, String correoElectronico, byte activo) {
       this.curp = curp;
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.correoElectronico = correoElectronico;
       this.activo = activo;
    }
   
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(byte activo) {
        this.activo = activo;
    }




}


